### ISSUE TITLE
ShadowMC Crash 1.8.9-3.0.0

### ISSUE THREAD

**Issue by WenXin20** [shadowfacts/ShadowMC#10]
Crash Log:
(https://github.com/shadowfacts/ShadowMC/files/111445/crash-2016-01-31_12.12.13-client.txt)

**Comment by shadowfacts** [comment]
Fixed in b10acf3c4503b6ed527b05cf9225e1e632446521. ShadowMC-1.8.9-3.0.0 BETA 2 will have this fix on CurseForge once it's approved.

**Comment by WenXin20** [comment]
Ok, thanks
