### ISSUE TITLE
ShadowMC & DiscordChat - Required on client.

### ISSUE THREAD

**Issue by Mohron** [shadowfacts/ShadowMC#12]
ShadowMC requires minecraft clients to have it installed even when it is only included on a server as a dependency of DiscordChat, a Server side only mod. This make the server side mod not usable on servers running non-custom modpacks.

Mod versions: 
ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar
DiscordChat-1.8.9-1.0.5.jar

Minecraft version: 
forge-1.8.9-11.15.1.1777

**Comment by shadowfacts** [comment]
Closed in favor of https://github.com/shadowfacts/DiscordChat/issues/25.
