### ISSUE TITLE
incompatibility (?) between ShadowMC and DiscordChat

### ISSUE THREAD

**Issue by 4rz0** [shadowfacts/ShadowMC#14]
Brief explanation of issue:
Minecraft crashes with latest ShadowMC and DiscordChat.
Downgrading ShadowMC to ShadowMC-1.9-3.1.4.jar "fixes" the problem.

Steps to reproduce:
- Step 1
  Install latest ShadowMC and DiscordChat
- Step 2
  Start game

Link to crash report (if applicable) on [gist](https://gist.github.com):
https://gist.github.com/4rz0/a90a026f8eaa19cc9092d324213122dc

Game-/Mod-Versions:
Minecraft 1.9
Forge 12.16.1.1898
ShadowMC-1.9-3.2.1.jar
DiscordChat-1.9-1.1.1.jar

**Comment by shadowfacts** [comment]
DiscordChat 1.2.0 will be released later today which will fix this.
