### ISSUE TITLE
Crash on latest version

### ISSUE THREAD

**Issue by MokahTGS** [shadowfacts/ShadowMC#16]
Brief explanation of issue:

Crash on load

Link to crash report (if applicable) on [gist](https://gist.github.com):

http://pastebin.com/mHbhsQvy

ShadowMC version:
3.4.2

Minecraft version:
1.10.2

**Comment by shadowfacts** [comment]
Extra Rails requires [3.4.4](http://minecraft.curseforge.com/projects/shadowmc/files/2316921)+
