### ISSUE TITLE
No idea, maybe points to shadowmc?

### ISSUE THREAD

**Issue by Divineaspect** [shadowfacts/ShadowMC#17]
Brief explanation of issue:
Server crash with no one on

Steps to reproduce:

Leave server on overnight... sorry all I got.

Link to crash report (if applicable) on [gist](https://gist.github.com): http://pastebin.com/8a7BpCFR
http://pastebin.com/jRttG548

ShadowMC version: 1.8.9-3.0.0 snapshot

Minecraft version: 1.8.9

may also relate to progression, I'll also be filing this with joshie.

**Comment by shadowfacts** [comment]
1. The crash isn't ShadowMC or DiscordChat.
2. The error in the log is DiscordChat not ShadowMC. (It's not even DiscordChat, it's a problem with JDA or your system b/c it can't load libopus)
3. 1.8.9 isn't supported any more

**Comment by Divineaspect** [comment]
Thanks for the quick reply
