### ISSUE TITLE
Crash on 1.10.2 Forge 2087

### ISSUE THREAD

**Issue by brisingraerowing** [shadowfacts/ShadowMC#18]
Brief explanation of issue:

Crash during initialization.

Steps to reproduce:
- Install forge 2087
- Install ShadowMC and a mod that uses it
- Try and launch the game

[Crash Report](https://gist.github.com/BrisingrAerowing/f62b8507c64c686c2e0b10c4826d8c85)

ShadowMC version: 3.4.4

Minecraft version: 1.10.2

**Comment by shadowfacts** [comment]
Endergizer requires my [Forgelin fork](https://minecraft.curseforge.com/projects/shadowfacts-forgelin).
