### ISSUE TITLE
Fatally Missing Blocks / Items (shadowmc:nuggetIron)

### ISSUE THREAD

**Issue by xenoflot** [shadowfacts/ShadowMC#21]
**Brief explanation of issue:**
Can't connect to server. Client reports that it's missing shadowmc:nuggetIron

* I have manually inspected server and client mod folders. Everything appears identical (except for a couple of server-side mods).
* I copied the client's entire config folder to the server and overwrote everything then fired up the server and restarted my client.
* No such errors in SSP

Log> Found a missing id from the world shadowmc:nuggetIron

These mods add an nuggetIron
* embers
* neotech

I think the problem only started happening when I added Embers.
I have now modified shadowmc.cfg to disable its nugget.

**Workaround**
So I seem to have worked around this problem by forcing shadowmc to disable its nugget, but I figure it's worth logging this ticket anyway so that you're aware there's a bug in the auto-disable.

ShadowMC version: 3.6.0
Minecraft version: 1.10.2
Forge: 2185
Embers-0.100
NeoTech-1.10.2-3.3.0

Server-side mods that I hope have no effect:
CustomMainMenu
CustomMOTD
DiscordChat
Modpatcher.jlib (Part of Tickprofiler)
NoMoreSpawningOnTrees
p455w0rdslib
Tickprofiler

**Comment by shadowfacts** [comment]
No longer possible, because the ShadowMC iron nugget doesn't exist in 1.11+.
