### ISSUE TITLE
My Minecraft keeps on crashing when I start it, and It say's that shadowmc made it crash

### ISSUE THREAD

**Issue by lalvstad** [shadowfacts/ShadowMC#23]
I downloaded shadowmc for minecraft, and when I try to play it it crashes. 

Steps to reproduce:

- Just playing minecraft with shadowmc in mods.

Crash Report:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ShadowMC (shadowmc)

ShadowMC version:3.7.5

Minecraft version:1.12.1

**Comment by shadowfacts** [comment]
Post the actual crash report.

**Comment by Tokeli** [comment]
Since he never did and I just encountered this on the same version, here's the crash report: https://gist.github.com/Tokeli/e01b88534e3781dff76f13d3a0f54d03

MC 1.12.1, ShadowMC 3.7.5, Forgelin 1.5.1, Forge 14.22.0.2474

**Comment by ghost** [comment]
Same problem here (also same versions). My [crash-log](https://paste.ee/p/9OM1o).

**Comment by Tokeli** [comment]
Pretty sure we both got our crashes because we were using the 1.11 version of ShadowMC in a 1.12 pack. 8) I think something on Curse has the wrong dependency, I would have had to go out of my way to download the wrong version.

**Comment by ghost** [comment]
You know what... you are right. :-o
