### ISSUE TITLE
Crash between this mod and Tough as Nails

### ISSUE THREAD

**Issue by Sunconure11** [shadowfacts/ShadowMC#24]
Brief explanation of issue:

The game crashes on startup with both this mod and TaN Installed

Steps to reproduce:

- Step 1: Install this mod + TaN
- Step 2: Crash

Link to crash report (if applicable) on [gist](https://gist.github.com):

https://pastebin.com/xnHHtCrT

ShadowMC version: 3.8.1

Minecraft version: 1.12.2

**Comment by TheSaucyWelshman** [comment]
I'm getting a similar crash without TaN.

https://pastebin.com/bSBZ6zRH

Forge: 14.23.1.2581
ShadowMC: 1.12.2-3.8.1

**Comment by shadowfacts** [comment]
Fixed in [ShadowMC 3.8.3](https://github.com/shadowfacts/ShadowMC/releases/tag/1.12.2-3.8.3).
