### ISSUE TITLE
crash wth shadowmc

### ISSUE THREAD

**Issue by SDUBZ** [shadowfacts/ShadowMC#25]
Brief explanation of issue:
crashes on launch

all details are here 
https://github.com/sargunv/level-up-hp/issues/5

**Comment by shadowfacts** [comment]
Fixed in [ShadowMC 3.8.3](https://github.com/shadowfacts/ShadowMC/releases/tag/1.12.2-3.8.3).

**Comment by SDUBZ** [comment]
are you sure its fixed? @shadowfacts 
[crash-2017-12-25_20.15.24-client.txt](https://github.com/shadowfacts/ShadowMC/files/1585645/crash-2017-12-25_20.15.24-client.txt)
