### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nexusdog** [shadowfacts/ShadowMC#26]
MC/F 1.12.2 2581

ShadowMC-1.12.2-3.8.1

'An unexpected error' crash message back to launcher

https://pastebin.com/B6PE3zh0

**Comment by shadowfacts** [comment]
Fixed in [ShadowMC 3.8.3](https://github.com/shadowfacts/ShadowMC/releases/tag/1.12.2-3.8.3).
