### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by ghost** [shadowfacts/ShadowMC#27]
[crash-2017-12-24_19.29.14-client.txt](https://github.com/shadowfacts/ShadowMC/files/1584947/crash-2017-12-24_19.29.14-client.txt)
report tells eveyrthing

**Comment by shadowfacts** [comment]
Fixed in [3.8.3](https://github.com/shadowfacts/ShadowMC/releases/tag/1.12.2-3.8.3).
